[ 2024-04-28 23:40:47,934 ] 91 root - INFO - Starting all threads
[ 2024-04-28 23:40:47,934 ] 91 root - INFO - Starting all threads
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Tosan', 'test_mode': False, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Tosan', 'test_mode': False, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Test mode: False
[ 2024-04-28 23:40:47,935 ] 91 root - INFO - Test mode: False
[ 2024-04-28 23:40:47,938 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-28 23:40:47,938 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-28 23:40:49,935 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:40:49,941 ] 91 root - INFO - Thread 0 started
[ 2024-04-28 23:40:49,941 ] 91 root - INFO - Thread 0 started
[ 2024-04-28 23:40:49,972 ] 91 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-28 23:40:49,974 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei1@gmail.com, Password: aichi@5921
[ 2024-04-28 23:40:51,284 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:40:51,961 ] 91 root - INFO - Thread 1 started
[ 2024-04-28 23:40:51,961 ] 91 root - INFO - Thread 1 started
[ 2024-04-28 23:40:51,969 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-28 23:40:51,970 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-28 23:40:53,625 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:40:53,972 ] 91 root - INFO - Thread 2 started
[ 2024-04-28 23:40:53,972 ] 91 root - INFO - Thread 2 started
[ 2024-04-28 23:40:56,258 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-28 23:40:57,435 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-28 23:40:59,800 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-28 23:41:07,286 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-28 23:41:08,763 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-28 23:41:09,652 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:41:10,999 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:41:11,050 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-28 23:41:11,941 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:41:12,891 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:41:13,536 ] 91 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-28 23:41:15,573 ] 91 main_controller - INFO - Browser opened
