[ 2024-04-24 15:00:46,720 ] 91 root - INFO - Starting all threads
[ 2024-04-24 15:00:46,720 ] 91 root - INFO - Starting all threads
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': '行政', 'test_mode': True, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': '行政', 'test_mode': True, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Test mode: True
[ 2024-04-24 15:00:46,721 ] 91 root - INFO - Test mode: True
[ 2024-04-24 15:00:46,724 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-24 15:00:46,724 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-24 15:00:48,722 ] 91 root - INFO - Thread 0 started
[ 2024-04-24 15:00:48,722 ] 91 root - INFO - Thread 0 started
[ 2024-04-24 15:00:48,811 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:00:54,995 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:00:58,941 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:00:58,945 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:00:59,262 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:00:59,262 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:00:59,498 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:00:59,498 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:00:59,503 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:01:01,089 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:01:01,106 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:01:01,167 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:01:03,394 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-24 15:01:05,348 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:01:10,941 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:01:14,205 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:01:14,210 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:01:14,516 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:01:14,516 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:01:14,769 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:01:14,769 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:01:14,774 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:01:15,875 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:01:15,894 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:01:15,940 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:01:18,151 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-24 15:01:20,112 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:01:25,621 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:01:29,636 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:01:29,643 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:01:29,961 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:01:29,962 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:01:30,211 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:01:30,211 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:01:30,216 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:01:32,126 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:01:32,143 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:01:32,169 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:01:34,398 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-24 15:01:36,406 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:01:41,935 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:01:46,048 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:01:46,054 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:01:46,366 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:01:46,366 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:01:46,620 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:01:46,620 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:01:46,625 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:01:48,433 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:01:48,452 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:01:48,478 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:01:50,701 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:01:52,646 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:01:58,209 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:02:01,914 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:02:01,924 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:02:02,243 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:02:02,245 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:02:02,602 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:02:02,604 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:02:02,673 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:02:04,874 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:02:04,910 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:02:05,031 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:02:07,261 ] 91 main_controller - INFO - Subprocess 0 started with trial number 5
[ 2024-04-24 15:02:09,337 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:02:14,890 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-24 15:02:18,411 ] 91 luthien5921 - INFO - Logging in
[ 2024-04-24 15:02:18,417 ] 91 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-24 15:02:18,731 ] 91 luthien5921 - INFO - Logged in finished
[ 2024-04-24 15:02:18,732 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:02:18,968 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_00_46\screenshot_luthien5921.png
[ 2024-04-24 15:02:18,969 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:02:18,973 ] 91 luthien5921 - INFO - On main page
[ 2024-04-24 15:02:20,281 ] 91 luthien5921 - INFO - Search submitted
[ 2024-04-24 15:02:20,306 ] 91 luthien5921 - INFO - Collected 2 forms
[ 2024-04-24 15:02:20,374 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 75, in __init__
    self.end_datetime = du.string_to_datetime(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:02:22,587 ] 91 main_controller - ERROR - Return since max number of retry reached 5
[ 2024-04-24 15:02:22,588 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:27,265 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:27,265 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:31,964 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:31,964 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:36,634 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:36,634 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:41,321 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:41,322 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:46,018 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:46,019 ] 91 main_controller - INFO - Closing browser
[ 2024-04-24 15:02:50,706 ] 91 main_controller - INFO - Browser closed
[ 2024-04-24 15:02:50,706 ] 91 root - INFO - All threads are done
[ 2024-04-24 15:02:50,706 ] 91 root - INFO - All threads are done
