[ 2024-04-23 22:40:01,958 ] 94 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-23 22:40:01,959 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: nihahi50@gmail.com, Password: hoahong1234
[ 2024-04-23 22:40:11,251 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:40:20,910 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:40:21,320 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_40_01\screenshot_nihahi50.png
[ 2024-04-23 22:40:21,322 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:40:24,330 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 22:40:24,331 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101'}]
[ 2024-04-23 22:40:24,332 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム'}
[ 2024-04-23 22:40:24,333 ] 82 main_controller - ERROR - Caught exception: __init__() missing 1 required positional argument: 'gender'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 89, in subprocess
    main_logger.info("Customer info index {}: {}".format(customer_index, customer_info))
TypeError: __init__() missing 1 required positional argument: 'gender'
[ 2024-04-23 22:40:24,335 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:40:24,335 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:40:25,515 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:40:25,515 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:40:34,824 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:40:34,824 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:40:35,204 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_40_01\screenshot_nihahi50.png
[ 2024-04-23 22:40:35,204 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_40_01\screenshot_nihahi50.png
[ 2024-04-23 22:40:35,204 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:40:35,204 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:40:38,037 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 22:40:38,037 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 22:40:38,037 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101'}]
[ 2024-04-23 22:40:38,037 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101'}]
[ 2024-04-23 22:40:38,038 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム'}
[ 2024-04-23 22:40:38,038 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム'}
[ 2024-04-23 22:40:38,038 ] 82 main_controller - ERROR - Caught exception: __init__() missing 1 required positional argument: 'gender'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 89, in subprocess
    customer = Customer.safe_load(**customer_info)
TypeError: __init__() missing 1 required positional argument: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 89, in subprocess
    customer = Customer.safe_load(**customer_info)
TypeError: __init__() missing 1 required positional argument: 'gender'
[ 2024-04-23 22:40:38,038 ] 82 main_controller - ERROR - Caught exception: __init__() missing 1 required positional argument: 'gender'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 89, in subprocess
    customer = Customer.safe_load(**customer_info)
TypeError: __init__() missing 1 required positional argument: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 89, in subprocess
    customer = Customer.safe_load(**customer_info)
TypeError: __init__() missing 1 required positional argument: 'gender'
[ 2024-04-23 22:40:38,047 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:40:38,047 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:40:38,047 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:40:39,000 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:40:39,000 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:40:39,000 ] 94 main_controller - INFO - Browser opened
