[ 2024-04-28 23:35:21,041 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-28 23:35:21,041 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:23,056 ] 91 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-28 23:35:23,056 ] 91 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-28 23:35:23,056 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei1@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:23,056 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei1@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:23,639 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:23,639 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:24,660 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:24,660 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:25,077 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-28 23:35:25,077 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-28 23:35:25,077 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-28 23:35:25,078 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:25,078 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:25,078 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:27,247 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:27,247 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:27,247 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:32,297 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:32,297 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:32,297 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:34,069 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:34,069 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:34,069 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:34,455 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:35:34,455 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:35:34,455 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:35:34,455 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:35:36,622 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:36,622 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:36,622 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:36,622 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
