[ 2024-04-30 23:21:51,600 ] 91 root - INFO - Starting all threads
[ 2024-04-30 23:21:51,600 ] 91 root - INFO - Starting all threads
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': '行政', 'test_mode': True, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': '行政', 'test_mode': True, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Number of dev accounts: 3
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Number of dev accounts: 3
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Test mode: True
[ 2024-04-30 23:21:51,601 ] 91 root - INFO - Test mode: True
[ 2024-04-30 23:21:51,605 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-30 23:21:51,605 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-30 23:21:53,614 ] 91 root - INFO - Thread 0 started
[ 2024-04-30 23:21:53,614 ] 91 root - INFO - Thread 0 started
[ 2024-04-30 23:21:53,617 ] 91 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-30 23:21:53,617 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei1@gmail.com, Password: aichi@5921
[ 2024-04-30 23:21:54,827 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:21:55,629 ] 91 root - INFO - Thread 1 started
[ 2024-04-30 23:21:55,629 ] 91 root - INFO - Thread 1 started
[ 2024-04-30 23:21:55,635 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-30 23:21:55,637 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-30 23:21:55,997 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:21:57,656 ] 91 root - INFO - Thread 2 started
[ 2024-04-30 23:21:57,656 ] 91 root - INFO - Thread 2 started
[ 2024-04-30 23:21:58,446 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:02,452 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-30 23:22:03,405 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-30 23:22:05,404 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-30 23:22:13,818 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:14,564 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:16,033 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-30 23:22:16,776 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-30 23:22:16,806 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:18,127 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:19,001 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:19,643 ] 91 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-30 23:22:21,440 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:24,129 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-30 23:22:24,963 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-30 23:22:28,067 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-30 23:22:35,279 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:36,396 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:37,484 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-30 23:22:38,602 ] 91 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-30 23:22:39,413 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:39,616 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:40,497 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:41,659 ] 91 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-30 23:22:43,062 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:22:45,407 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-30 23:22:48,045 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-30 23:22:49,093 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-30 23:22:56,480 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:59,409 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:22:59,774 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-30 23:23:00,282 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:23:02,031 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:02,274 ] 91 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-30 23:23:02,708 ] 91 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-30 23:23:03,685 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:04,968 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:07,800 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-30 23:23:11,175 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-30 23:23:13,534 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-30 23:23:15,270 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.63)
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E48DB4F]
	(No symbol) [0x00007FF72E531087]
	(No symbol) [0x00007FF72E548871]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-30 23:23:16,111 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.63)
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E48DB4F]
	(No symbol) [0x00007FF72E531087]
	(No symbol) [0x00007FF72E548871]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-30 23:23:17,491 ] 91 main_controller - INFO - Subprocess 2 started with trial number 4
[ 2024-04-30 23:23:18,787 ] 91 main_controller - INFO - Subprocess 1 started with trial number 4
[ 2024-04-30 23:23:18,792 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:19,099 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:23:20,872 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:21,462 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-30 23:23:23,039 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:24,457 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-30 23:23:26,873 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-30 23:23:29,149 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-30 23:23:35,503 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.63)
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E48DB4F]
	(No symbol) [0x00007FF72E531087]
	(No symbol) [0x00007FF72E548871]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:23:37,733 ] 91 main_controller - INFO - Subprocess 2 started with trial number 5
[ 2024-04-30 23:23:38,253 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.63)
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E48DB4F]
	(No symbol) [0x00007FF72E531087]
	(No symbol) [0x00007FF72E548871]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:23:38,823 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:40,326 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, TimeoutException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 29, in login
    wait_until_presence(browser, By.ID, "userLoginForm.userId")
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\html_utils.py", line 8, in wait_until_presence
    WebDriverWait(browser, timeout).until(EC.presence_of_element_located((by, html)))
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF72E94F922+3045234]
	(No symbol) [0x00007FF72E5F3652]
	(No symbol) [0x00007FF72E4B7564]
	(No symbol) [0x00007FF72E505F9D]
	(No symbol) [0x00007FF72E50606C]
	(No symbol) [0x00007FF72E54BDD7]
	(No symbol) [0x00007FF72E529DEF]
	(No symbol) [0x00007FF72E5491C4]
	(No symbol) [0x00007FF72E529B53]
	(No symbol) [0x00007FF72E4F813C]
	(No symbol) [0x00007FF72E4F8D71]
	GetHandleVerifier [0x00007FF72E97E89D+3237613]
	GetHandleVerifier [0x00007FF72E9C0BA7+3508727]
	GetHandleVerifier [0x00007FF72E9B976F+3478975]
	GetHandleVerifier [0x00007FF72E72F1C6+815126]
	(No symbol) [0x00007FF72E5FED0F]
	(No symbol) [0x00007FF72E5F9854]
	(No symbol) [0x00007FF72E5F99E2]
	(No symbol) [0x00007FF72E5EA574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 53, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, TimeoutException found
[ 2024-04-30 23:23:40,593 ] 91 main_controller - INFO - Subprocess 1 started with trial number 5
[ 2024-04-30 23:23:42,867 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:43,167 ] 91 main_controller - INFO - Subprocess 0 started with trial number 5
[ 2024-04-30 23:23:44,653 ] 91 main_controller - INFO - Browser opened
[ 2024-04-30 23:23:44,942 ] 91 luthien5921+shinsei2 - INFO - Opened login page
