[ 2024-04-24 15:03:54,411 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-24 15:03:54,412 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-24 15:03:56,745 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:07,014 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:07,237 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:07,237 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:08,853 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:11,062 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-24 15:04:11,062 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-24 15:04:13,209 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:13,209 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:23,389 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:23,389 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:23,605 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:23,605 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:23,606 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:23,606 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:25,481 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:25,481 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:27,697 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-24 15:04:27,697 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-24 15:04:27,697 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-24 15:04:29,807 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:29,807 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:29,807 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:39,793 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:39,793 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:39,793 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:40,016 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:40,016 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:40,016 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:40,017 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:40,017 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:40,017 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:41,881 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:41,881 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:41,881 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:44,096 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-24 15:04:44,096 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-24 15:04:44,096 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-24 15:04:44,096 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-24 15:04:46,054 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:46,054 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:46,054 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:46,054 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:04:55,936 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:55,936 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:55,936 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:55,936 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-24 15:04:56,129 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:56,129 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:56,129 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:56,129 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_24\15_03_54\screenshot_luthien5921.png
[ 2024-04-24 15:04:56,130 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:56,130 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:56,130 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:56,130 ] 91 main_controller - INFO - Finding forms
[ 2024-04-24 15:04:57,660 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:57,660 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:57,660 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:57,660 ] 79 main_controller - ERROR - Caught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 25, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 58, in _collect
    form_info = self._parse_data(form_text)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 97, in _parse_data
    form_info = FormInfo(title, status, start_date_str, end_date_str, template_seq)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\models\form.py", line 79, in __init__
    self.end_date = du.string_to_date(end_date_str)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\utils\data_utils.py", line 57, in string_to_datetime
    year = int(match_date.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[ 2024-04-24 15:04:59,876 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:04:59,876 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:04:59,876 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:04:59,876 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:04:59,876 ] 91 main_controller - INFO - Subprocess 0 started with trial number 4
[ 2024-04-24 15:05:01,964 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:05:01,964 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:05:01,964 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:05:01,964 ] 91 main_controller - INFO - Browser opened
[ 2024-04-24 15:05:01,964 ] 91 main_controller - INFO - Browser opened
