[ 2024-04-16 05:25:16,719 ] 94 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-16 05:25:16,720 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: Nickpown0411@gmail.com, Password: hoahong1234
[ 2024-04-16 05:25:18,787 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-16 05:25:18,787 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-16 05:25:18,794 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: marjyamada040493@gmail.com, Password: Marj0409
[ 2024-04-16 05:25:18,794 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: marjyamada040493@gmail.com, Password: Marj0409
[ 2024-04-16 05:25:19,123 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:25:19,123 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:25:20,286 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:25:20,286 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:25:20,785 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-16 05:25:20,785 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-16 05:25:20,785 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-16 05:25:28,935 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:28,935 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:28,935 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_Nickpown0411.png
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_Nickpown0411.png
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_Nickpown0411.png
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:29,082 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:29,982 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:29,982 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:29,982 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_marjyamada040493.png
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_marjyamada040493.png
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\05_25_16\screenshot_marjyamada040493.png
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:30,138 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 05:25:31,181 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:25:31,181 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:25:31,181 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:25:32,808 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:25:32,808 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:25:32,808 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-16 05:26:00,034 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:00,034 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:00,034 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:00,035 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:00,035 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:00,035 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95608
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:03,707 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:25,792 ] 82 main_controller - ERROR - Caught exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]

[ 2024-04-16 05:26:25,792 ] 82 main_controller - ERROR - Caught exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]

[ 2024-04-16 05:26:25,792 ] 82 main_controller - ERROR - Caught exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]

[ 2024-04-16 05:26:25,801 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-16 05:26:25,801 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-16 05:26:25,801 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-16 05:26:25,801 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95604
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95604
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95604
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Failed to fill form, template sequence: 95604
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:26,636 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-16 05:26:27,367 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:26:27,367 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:26:27,367 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:26:27,367 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 05:26:34,040 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 19, in login
    while browser.current_url != URLs.login_url:
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 57, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-16 05:26:34,040 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 19, in login
    while browser.current_url != URLs.login_url:
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 57, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-16 05:26:34,040 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 19, in login
    while browser.current_url != URLs.login_url:
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 57, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-16 05:26:34,040 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchWindowException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 80, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 52, in fill
    browser.refresh()
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 570, in refresh
    self.execute(Command.REFRESH)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 19, in login
    while browser.current_url != URLs.login_url:
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770B6CA7C]
	(No symbol) [0x00007FF770BFD687]
	(No symbol) [0x00007FF770C12AC1]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 57, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchWindowException found
[ 2024-04-16 05:26:34,049 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-16 05:26:34,049 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-16 05:26:34,049 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-16 05:26:34,049 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-16 05:26:34,049 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
