[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Starting all threads
[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Starting all threads
[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'gen', 'test_mode': True, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_hash': '080-1583-0891', 'uc': True, 'headless': False, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'gen', 'test_mode': True, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_hash': '080-1583-0891', 'uc': True, 'headless': False, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Number of dev accounts: 1
[ 2024-04-16 04:37:43,363 ] 94 root - INFO - Number of dev accounts: 1
[ 2024-04-16 04:37:43,365 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-16 04:37:45,383 ] 94 root - INFO - Thread 0 started
[ 2024-04-16 04:37:45,383 ] 94 root - INFO - Thread 0 started
[ 2024-04-16 04:37:46,084 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 04:38:52,243 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, InvalidSessionIdException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 24, in login
    browser.get(URLs.login_url)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 396, in uc_special_open_if_cf
    driver.switch_to.window(driver.window_handles[-1])
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 494, in window_handles
    return self.execute(Command.W3C_GET_WINDOW_HANDLES)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EB1D]
	(No symbol) [0x00007FF770BC7E27]
	(No symbol) [0x00007FF770BF6E89]
	(No symbol) [0x00007FF770BF12AB]
	(No symbol) [0x00007FF770BF0C76]
	(No symbol) [0x00007FF770B62E55]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770B61E90]
	GetHandleVerifier [0x00007FF771209958+4792216]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 52, in subprocess
    return
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, InvalidSessionIdException found
[ 2024-04-16 04:38:52,246 ] 94 main_controller - INFO - Closing browser
[ 2024-04-16 04:38:54,380 ] 94 main_controller - INFO - Browser closed
